@ECHO OFF

SET SCRIPT_FOLDER=%~dp0
SET SCRIPT_FOLDER=%SCRIPT_FOLDER:~,-1%

CALL :GET_FULL_PATH %SCRIPT_FOLDER%\..\..\..\intermediate\staging
SET SRC_PUBLISH_FOLDER=%GET_FULL_PATH_RESULT%
SET DST_PUBLISH_FOLDER=\\contoso\studio\ipoint\VisualXpress

IF "%1"=="RC" (
    SHIFT
    SET DST_PUBLISH_FOLDER=%DST_PUBLISH_FOLDER%\%1
)

xcopy.exe /F /S /Y "%SRC_PUBLISH_FOLDER%" "%DST_PUBLISH_FOLDER%\"

:PAUSE_END
IF "%1"=="" pause
GOTO :EOF

:GET_FULL_PATH
SET GET_FULL_PATH_RESULT=%~fp1
GOTO :EOF
