@ECHO OFF
SETLOCAL ENABLEDELAYEDEXPANSION

SET VSIXINSTALLER_EXE=
FOR %%V IN (15.0 14.0 12.0) DO (
	FOR /F "tokens=2*" %%A IN ('reg query HKLM\Software\Wow6432Node\Microsoft\VisualStudio\SxS\VS7 /v %%V ^| FIND "REG_SZ"') DO (
		SET VSIXINSTALLER_EXE=%%B\Common7\IDE\VSIXInstaller.exe
		IF EXIST "!VSIXINSTALLER_EXE!" GOTO :FOUND_VSIXINSTALLER
	)
)
ECHO Failed to find VSIXInstaller.exe
PAUSE
GOTO :EOF

:FOUND_VSIXINSTALLER
SET UNINSTALL_CMD="!VSIXINSTALLER_EXE!" /uninstall:87cfaa4e-e594-4b22-a745-f8dd9be5038b
ECHO !UNINSTALL_CMD!
!UNINSTALL_CMD!
