@ECHO OFF
SETLOCAL ENABLEDELAYEDEXPANSION

SET VSWHERE_EXE=%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe
SET VSIXINSTALLER_EXE=
FOR /F "tokens=*" %%A IN ('"%VSWHERE_EXE%" -sort -property InstallationPath') DO (
	SET VSIXINSTALLER_EXE=%%A\Common7\IDE\VSIXInstaller.exe
	IF EXIST "!VSIXINSTALLER_EXE!" GOTO :FOUND_VSIXINSTALLER
)
ECHO Failed to find VSIXInstaller.exe
PAUSE
GOTO :EOF

:FOUND_VSIXINSTALLER
SET UNINSTALL_CMD="!VSIXINSTALLER_EXE!" /uninstall:87cfaa4e-e594-4b22-a745-f8dd9be5038b
ECHO !UNINSTALL_CMD!
!UNINSTALL_CMD!
